name: Submit Packages en Masse
on:
  workflow_dispatch:
jobs:
  Package-Submission:
    runs-on: windows-latest
    env: 
      KOMAC_TOKEN: ${{ secrets.PR_TOKEN }}
      PACKAGE_ID: ${{ matrix.package_id }}
      PACKAGE_VERSION: ${{ matrix.package_versions }}
      PACKAGE_URL: "https://downloads.topazlabs.com/deploy/TopazPhotoAI/${{ matrix.package_versions }}/TopazPhotoAI-${{ matrix.package_versions }}.msi"
    strategy:
      matrix:
        package_versions:
            # - 1.0.7
            # - 1.0.8
            - 1.0.9
            # - 1.1.0
            # - 1.1.1
            # - 1.1.3
            # - 1.1.4
            # - 1.1.5
            # - 1.1.6
            # - 1.1.7
            # - 1.1.8
            # - 1.1.9
            # - 1.2.0
            # - 1.2.1
            # - 1.2.10
            # - 1.2.2
            # - 1.2.3
            # - 1.2.4
            # - 1.2.5
            # - 1.2.6
            # - 1.2.7
            # - 1.2.8
            # - 1.2.9
            # - 1.3.0
            # - 1.3.1
            # - 1.3.10
            # - 1.3.11
            # - 1.3.12
            # - 1.3.2
            # - 1.3.3
            # - 1.3.4
            # - 1.3.5
            # - 1.3.6
            # - 1.3.7
            # - 1.3.8
            # - 1.3.9
            # - 1.4.0
            # - 1.4.1
            # - 1.4.2
            # - 1.4.3
            # - 1.5.0
            # - 1.5.1
            # - 1.5.2
            # - 1.5.3
            # - 1.5.4
            # - 2.0.0
            # - 2.0.1
            # - 2.0.2
            # - 2.0.3
            # - 2.0.4
            # - 2.0.5
            # - 2.0.6
            # - 2.0.7
            # - 2.1.0
            # - 2.1.1
            # - 2.1.2
            # - 2.1.3
            # - 2.1.4
            # - 2.2.0
            # - 2.2.1
            # - 2.2.2
            # - 2.3.0
        package_id:
            - TopazLabs.TopazPhotoAI
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Variables
          run: |
            echo "Package ID: $PACKAGE_ID"
            echo "Package Version: $PACKAGE_VERSION"
            echo "Package URL: $PACKAGE_URL"
        # # - name: Run Komac
        # #   uses: michidk/run-komac@v1
        # #   with:
        # #     args: 'update --token="$KOMAC_TOKEN" -i "$PACKAGE_ID" -v "$PACKAGE_VERSION" -u "$PACKAGE_URL" --submit'
        # - name: Install Komac
        #   run: |
        #     winget install komac --disable-interactivity --accept-source-agreements
        # - name: LS everything
        #   run: |
        #     ls -lRa
        # - name: Add token to Komac
        #   run: |
        #     komac token update --token={{ secrets.PR_TOKEN }}
        # - name: Generate Manifest and Submit
        #   run: |
        #     komac update --token={{ secrets.PR_TOKEN }} -i "{{ matrix.package_id }}" -v "{{ matrix.package_versions }}" -u "https://downloads.topazlabs.com/deploy/TopazPhotoAI/{{ matrix.package_versions }}/TopazPhotoAI-{{ matrix.package_versions }}.msi" --submit
        # - name: Remove token from Komac
        #   run: |
        #     komac token remove --yes
        - name: Install winget
          run : |
            Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
            Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
            Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.7.3/Microsoft.UI.Xaml.2.7.x64.appx -OutFile Microsoft.UI.Xaml.2.7.x64.appx
            Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.6.3482/24146eb205d040e69ef2d92d7034d97f_License1.xml -OutFile 24146eb205d040e69ef2d92d7034d97f_License1.xml
            Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
            Add-AppxPackage Microsoft.UI.Xaml.2.7.x64.appx
            Add-AppxProvisionedPackage -Online -PackagePath Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle  -LicensePath 24146eb205d040e69ef2d92d7034d97f_License1.xml -dependencypackagepath Microsoft.VCLibs.x64.14.00.Desktop.appx
            $ResolveWingetPath = (Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe").Path
            $then = get-date; $erroraction = 'silentlyContinue'; do {start-sleep -seconds 5;$wgr = . $resolvewingetpath\winget.exe} while (!$wgr);$now=get-date; $elapsed = $now-$then;write-output "Took $($elapsed.minutes) minutes and $($elapsed.seconds) seconds for WinGet to work. Started working at $($now)"
        - name: Install Komac
          run: winget install komac --disable-interactivity --accept-source-agreements
        - name: Add token to Komac
          run: komac token update --token=$KOMAC_TOKEN
