name: Submit Packages en Masse
on:
  workflow_dispatch:
jobs:
  Package-Submission:
    runs-on: windows-latest
    strategy:
      matrix:
        package_versions:
            - 1.0.7
            # - 1.0.8
            # - 1.0.9
            # - 1.1.0
            # - 1.1.1
            # - 1.1.3
            # - 1.1.4
            # - 1.1.5
            # - 1.1.6
            # - 1.1.7
            # - 1.1.8
            # - 1.1.9
            # - 1.2.0
            # - 1.2.1
            # - 1.2.10
            # - 1.2.2
            # - 1.2.3
            # - 1.2.4
            # - 1.2.5
            # - 1.2.6
            # - 1.2.7
            # - 1.2.8
            # - 1.2.9
            # - 1.3.0
            # - 1.3.1
            # - 1.3.10
            # - 1.3.11
            # - 1.3.12
            # - 1.3.2
            # - 1.3.3
            # - 1.3.4
            # - 1.3.5
            # - 1.3.6
            # - 1.3.7
            # - 1.3.8
            # - 1.3.9
            # - 1.4.0
            # - 1.4.1
            # - 1.4.2
            # - 1.4.3
            # - 1.5.0
            # - 1.5.1
            # - 1.5.2
            # - 1.5.3
            # - 1.5.4
            # - 2.0.0
            # - 2.0.1
            # - 2.0.2
            # - 2.0.3
            # - 2.0.4
            # - 2.0.5
            # - 2.0.6
            # - 2.0.7
            # - 2.1.0
            # - 2.1.1
            # - 2.1.2
            # - 2.1.3
            # - 2.1.4
            # - 2.2.0
            # - 2.2.1
            # - 2.2.2
            # - 2.3.0
        package_id:
            - TopazLabs.TopazPhotoAI
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: winget
          shell: powershell
          run: |
            # Install NtObjectManager module
            Install-Module NtObjectManager -Force
            # Install winget
            $vclibs = Invoke-WebRequest -Uri "https://store.rg-adguard.net/api/GetFiles" -Method "POST" -ContentType "application/x-www-form-urlencoded" -Body "type=PackageFamilyName&url=Microsoft.VCLibs.140.00_8wekyb3d8bbwe&ring=RP&lang=en-US" -UseBasicParsing | Foreach-Object Links | Where-Object outerHTML -match "Microsoft.VCLibs.140.00_.+_x64__8wekyb3d8bbwe.appx" | Foreach-Object href
            $vclibsuwp = Invoke-WebRequest -Uri "https://store.rg-adguard.net/api/GetFiles" -Method "POST" -ContentType "application/x-www-form-urlencoded" -Body "type=PackageFamilyName&url=Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe&ring=RP&lang=en-US" -UseBasicParsing | Foreach-Object Links | Where-Object outerHTML -match "Microsoft.VCLibs.140.00.UWPDesktop_.+_x64__8wekyb3d8bbwe.appx" | Foreach-Object href
            Invoke-WebRequest $vclibsuwp -OutFile Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe.appx
            Invoke-WebRequest $vclibs -OutFile Microsoft.VCLibs.140.00_8wekyb3d8bbwe.appx
            Add-AppxPackage -Path .\Microsoft.VCLibs.140.00.UWPDesktop_8wekyb3d8bbwe.appx
            Add-AppxPackage -Path .\Microsoft.VCLibs.140.00_8wekyb3d8bbwe.appx
            Invoke-WebRequest https://github.com/microsoft/winget-cli/releases/download/v1.0.11451/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
            Add-AppxPackage -Path .\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle
            # Create reparse point
            $installationPath = (Get-AppxPackage Microsoft.DesktopAppInstaller).InstallLocation
            Set-ExecutionAlias -Path "C:\Windows\System32\winget.exe" -PackageName "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe" -EntryPoint "Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget" -Target "$installationPath\AppInstallerCLI.exe" -AppType Desktop -Version 3
            explorer.exe "shell:appsFolder\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe!winget"
        - run: |
            winget --info
        - name: Install Komac
          run: |
            winget install komac --disable-interactivity --accept-source-agreements
        - name: Add token to Komac
          run: |
            komac token update --token={{ secrets.PR_TOKEN }}
        - name: Generate Manifest and Submit
          run: |
            komac update -i "{{ matrix.package_id }}" -v "{{ matrix.package_versions }}" -u "https://downloads.topazlabs.com/deploy/TopazPhotoAI/{{ matrix.package_versions }}/TopazPhotoAI-{{ matrix.package_versions }}.msi" --submit
        - name: Remove token from Komac
          run: |
            komac token remove --yes
