name: Submit Packages en Masse
on:
  workflow_dispatch:
jobs:
  Package-Submission:
    runs-on: ubuntu-latest
    env: 
      KOMAC_TOKEN: ${{ secrets.PR_TOKEN }}
      PACKAGE_ID: ${{ matrix.package_id }}
      PACKAGE_VERSION: ${{ matrix.package_versions }}
      PACKAGE_URL: "http://qmmp.ylsoftware.com/files/windows/2.0/qmmp-${{ matrix.package_versions }}-win32.exe"
    strategy:
      matrix:
        package_versions:
            - 2.0.4
            - 2.0.3
        package_id:
            - QmmpDevelopmentTeam.qmmp
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Variables
          run: |
            echo "Package ID: $PACKAGE_ID"
            echo "Package Version: $PACKAGE_VERSION"
            echo "Package URL: $PACKAGE_URL"
        - name: Get the damn thing
          run: |
            wget "https://github.com/russellbanks/Komac/releases/download/nightly/KomacPortable-linux-nightly-x64.tar.gz"
            tar -xzf KomacPortable-linux-nightly-x64.tar.gz
            mv KomacPortable-linux-nightly-x64 komac
            rm KomacPortable-linux-nightly-x64.tar.gz
        - name: Generate Manifest and Submit
          run: |
            ./komac update --token=$KOMAC_TOKEN -i "$PACKAGE_ID" -v $PACKAGE_VERSION -u "$PACKAGE_URL" --submit