name: Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Package-Scanning:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alphabet:
          - a
          - b
          - c
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print letter
        run: 'echo ${{ matrix.alphabet }}'
      - name: Get Winget-PKGs repo
        run: 'git clone https://github.com/microsoft/winget-pkgs'
      - name: Run checker script
        run: |
          chmod +x ./scripts/package_check.sh
          ./scripts/package_check.sh ${{ matrix.alphabet }}