name: Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Package-Scanning:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alphabet:
          # - a
          # - b
          # - c
          # - d
          # - e
          # - f
          # - g
          # - h
          # - i
          # - j
          # - k
          # - l
          # - m
          # - n
          # - o
          # - p
          # - q
          # - r
          # - s
          # - t
          # - u
          # - v
          # - w
          # - x
          # - y
          # - z
          - 0
          - 1
          - 2
          # - 3
          - 4
          - 5
          - 6
          - 7
          - 8
        #   - 9
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print letter
        run: 'echo ${{ matrix.alphabet }}'
      - name: Get Winget-PKGs repo
        run: 'git clone https://github.com/microsoft/winget-pkgs'
      - name: Checker script permissions
        run: |
          chmod +x ./scripts/package_check.sh
      - name: Run checker script
        run: |
          ./scripts/package_check.sh ${{ matrix.alphabet }}
      - name: List failed urls
        run: |
          cat fails.csv | sort | uniq > fails_sorted.csv
          cat fails_sorted.csv
      - name: Upload failed urls artifact
        uses: actions/upload-artifact@v4
        with:
          name: failed_urls_${{ matrix.alphabet }}
          path: fails_sorted.csv
          if-no-files-found: ignore
          retention-days: 1
  Compose-Artifacts:
    runs-on: ubuntu-latest
    needs: Package-Scanning
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Get all artifacts
          uses: actions/download-artifact@v4
        - name: Compose all artifacts
          run: |
              ls -lhR ~
              cat failed_urls_*/* > all_failed_urls.csv
              cat all_failed_urls.csv
        - name: Upload final artifact
          uses: actions/upload-artifact@v4
          with:
              name: all_failed_urls
              path: all_failed_urls.csv
              retention-days: 1